# Generated by Django 5.1.4 on 2025-03-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_pessoa_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='telefone',
            new_name='email',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
