# Generated by Django 5.1.4 on 2025-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_telefone_perfil_email_perfil_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
