# Generated by Django 5.1.4 on 2025-03-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_perfil_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='email',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
    ]
