# Generated by Django 5.1.4 on 2025-03-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_email_perfil_telefone_remove_perfil_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='telefone',
            new_name='email',
        ),
    ]
