# Generated by Django 5.1.4 on 2025-03-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_perfil_cidade_perfil_codigopostal_perfil_morada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='utilizador',
        ),
    ]
