# Generated by Django 5.1.4 on 2025-03-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_perfil_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='username',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
