# Generated by Django 5.1.4 on 2025-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_perfil_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='data_registro',
            new_name='dataregistro',
        ),
        
    ]
