# Generated by Django 5.1.4 on 2025-03-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_perfil_user_id'),
    ]

    operations = [

    ]
