# Generated by Django 5.1.4 on 2025-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.CharField(max_length=35),
        ),
    ]
