# Generated by Django 5.1.4 on 2025-03-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_alter_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
