# Generated by Django 5.1.4 on 2025-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_perfil_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
