# Generated by Django 5.1.4 on 2025-03-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_aula_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='fim',
        ),
    ]
